dist: trusty
sudo: required
language: c
compiler:
  - gcc
install:
  - git clone git://git.cryptomilk.org/projects/cmocka.git 
  - mkdir build
  - cmake ..
  - make
  - sudo make install
  - sudo apt-get install uthash-dev
before_script:
  - cmake -version
  - make --version 
  - gcc --version
  - mkdir build
  - cd build
  - cmake ..
script: make && make test
