dist: trusty
sudo: required
language: c
compiler:
  - gcc
before_install:
  - git clone git://git.cryptomilk.org/projects/cmocka.git 
install:
  - sudo apt-get install -y uthash-dev
  - cd cmocka
  - mkdir build
  - cmake .. && make && sudo make install
before_script:
  - cmake -version
  - make --version 
  - gcc --version
  - mkdir build
  - cd build
  - cmake ..
script: make && make test
