dist: xenial
sudo: required
language: c
compiler:
  - gcc
before_install:
install:
  - sudo apt-get install -y uthash-dev libcmocka-dev
before_script:
  - cmake -version
  - make --version 
  - gcc --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
script: make && ctest --verbose
